version: '3.8'

services:
  products-db:
    image: mongo:latest
    container_name: products_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: product-service
    ports:
      - 27017:27017
  
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service